### ISSUE TITLE
Invoice ID of less than 3 characters fails validation

### ISSUE THREAD

**Issue by cdahlin** [omnimodular/spec#5]
Right now, an `id` of length less than 3 fails the validation.

This fails some of our current test invoices as well, so an `id` of length 1 or 2 should be valid. It's also specified as part of `restricted-string` that the length should be 1-50, so our regex should reflect this.

https://github.com/omnimodular/spec/blob/5beb9b7505b804fe54ef100fa6db81b44fd12ddc/invoice-spec.json#L16-L20

**Comment by hholst80** [comment]
What should we do here.
1) remove the regexp limit and allow 1 character long `id` and `site`. note that then `site` cannot be used as-is as queue name rather it has to be checked/prepended with something to ensure that it is a valid queue name.
2) divide restricted-string into two classes: restricted-string-1-50 and restricted-string-3-50
3) <strike>disallow id of length less than 3.</strike>

**Comment by hholst80** [comment]
@chomni Let us reflect on this. Right now I feel that 1 would be the best option.

**Comment by hholst80** [comment]
Closed by #6
